# print("Enter your numbers to find sum:")
# a=input("enter number 1st:") #you should do typecasting while takin inputs default input is it will take it as string
# b=input("enter number 2nd:")
# print("sum is",int(a)+int(b))
name=("his name is john but he said he is gyanu!!")
# print(name[0:3])
# print(name[1:3])
# print(len(name))
# print(name[0:len(name)-1])

# # #loops
# # for character in name:
# #  print(character)
# # print(name.upper())
# # print(name.rstrip("!!"))
# # print(name.replace("gyanu","Anil"))
# # print(name.split(" "))
# # print(name.capitalize())
# print(name.center(100))
# print(name.count(" is"))
# print(name.endswith("newton"))
# print(name.startswith("his"))
# print(name.find("is"))
# print(name.isalnum())
# print(name.isalpha())
# print(name.islower())
# print(name.isprintable())
# print(name.isspace())
# print(name.istitle())
# print(name.isupper())
# print(name.swapcase())
# print(name.title())